apiVersion: v1
kind: Service
metadata:
  name: apphostinglab
  labels:
    app: apphostinglab 
spec:
  selector:
    app: apphostinglab
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30082
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apphostinglab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apphostinglab
    spec:
      containers:
      - name: apphostinglab
        image: jakobehn/activeazureacademylabmultiregion:1.0
        ports:
        - containerPort: 80
        env:
        - name: regionName
          value: "West Europe"        
   